site_name: Embedded Progress
site_url: https://abrar74774.github.io/embedded-progress

theme:
  name: material

  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - blog

nav:
  - Welcome: index.md
  - Projects:
      - blog/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.tasklist
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css
